### ISSUE TITLE
ebesucher contaner wird erstellt und anschließend wieder gelöscht

### ISSUE THREAD

**Issue by copystring** [Pakobbix/passive-income#2]
Hallo,

heute habe ich endlich mal dein Script ausprobiert. Ich brauche nur eBesucher. Leider klappt das nicht.
Ich folge den Anweisungen. Hinterlege im Firefox vom Docker Container meinen Benutzernamen und setze den Haken bei Privacy.
Das Script läuft dann entsprechend weiter. Der Docker Container ist beim Einrichten über das Script auch da, aber wenn er fertig ist, dann nicht mehr. Wenn ich es dann erneut durchführe, hat er sich meinen Benutzernamen in Firefox und den Haken bei Privacy gemerkt. 

In dem Dialog, in dem steht, dass ich 192.168.1.12:3000 aufrufen soll, existiert der Docker Container.
Irgendwann bin ich dann bei dem Dialog angelangt, in dem dies hier steht:  „Erstelle Sicherung und Lade Restarter Skript“.
Das bestätige ich mit OK. Dann dauert es ein paar Sekunden und der Dialog sieht dann so aus: 
![image](https://user-images.githubusercontent.com/1298861/224517109-94368ecc-3360-4c47-ac1e-e5de6c7196fe.png)
Ab dem Moment ist auch der Docker Container weg.
Ich folge brav allen weiteren Dialogen, bis alles fertig ist.
Als Ergebnis habe ich das hier: 

```
bash <(curl -fsSL https://raw.githubusercontent.com/Pakobbix/passive-income/master/gui_start.sh)


Ordner ebesucher exestiert bereits
Error response from daemon: No such container: ebesucher
4609255f6648056beda49a41f9629c627c4fafbba2609db5f4359f124e463268
grep: /tmp/updatecron: No such file or directory
crontab: usage error: no arguments permitted after this option
usage:  crontab [-u user] file
        crontab [ -u user ] [ -i ] { -e | -l | -r }
                (default operation is replace, per 1003.2)
        -e      (edit user's crontab)
        -l      (list user's crontab)
        -r      (delete user's crontab)
        -i      (prompt before deleting user's crontab)
rm: cannot remove '/tmp/crontab': No such file or directory


=====================================================================================================================================================================================================
1 Erfolgreiche Operationen
0 Fehlerhafte Operationen
1 Übersprungene Operationen
=====================================================================================================================================================================================================
```

Installiert habe ich ubuntu 22.04 als LXC in Proxmox
Watchtower ist dann übrigens auch nicht da.

Kannst du mir hier weiter helfen?

**Comment by redalert99** [comment]
Hallo,

ist bei mir genauso. Der Cronjob für den restart wird auch nicht angelegt.
restart.sh auszuführen bringt auch nichts, bricht mit fehler ab.

grüße

**Comment by Pakobbix** [comment]
Eure beiden Probleme sollten nun behoben worden sein.

Ich weiß nicht was genau da geschehen ist, aber als ich den restarter und das skript aktualisiert hatte, wurde nur der restarter von git übernommen. Die Änderungen von der gui wurden nicht übernommen bzw. durch eine alte Datei ersetzt, was zu diesem Problem führte. 


Ich habe soweit alles gefixt, es gibt nur noch ein Problem bezgl. der ausgewählten Sprachformatierung (wenn nicht deutsch installiert ist) dann wird nach der Übersicht aller Services das Service Auswahlmenü nicht angezeigt (Einter drücken).

**Comment by copystring** [comment]
OK. Das sieht etwas besser aus. Der Container wurde nun sauber erstellt und ist auch, nachdem alles fertig ist noch da.
Aber kein watchdog. Der fehlt. Des Weiteren muss der eBesucher Container manuell gestartet werden.
Außerdem sollte die Sprache von Firefox (manuell) auf Deutsch eingestellt werden, damit eBesucher sauber arbeitet. :)

**Comment by Pakobbix** [comment]
Das:

> Der Container wurde nun sauber erstellt und ist auch, nachdem alles fertig ist noch da.

und das :

> Des Weiteren muss der eBesucher Container manuell gestartet werden.

Schließt sich gegenseitig aus.
Denn der Container wird beendet, damit das Firefox Profil gesichert werden kann, und dann per restarter wieder gestartet.

Also entweder funktioniert der Restarter, bedeutet, nach dem erstellen ist der Container da, oder er funktioniert nicht und dann kann der Container nicht da sein, das müsstest du nochmal austesten (`bash /root/ebesucher/restarter.sh`). Wenn das funktioniert, was genau muss dann mauell gestartet werden?

Das Skript checkt eigentlich, ob einer der Services läuft und falls ja, wird Watchtowerr ebenfalls erstellt. 
Da ich das ebenfalls überprüft hatte (War ja ebenfalls in der 1. Meldung) bräuchte ich auch hier mehr Infos. Wurde es einfach übersprungen, gabs eine Fehlermeldung, oder wurde der Container eventuell erstellt aber nicht gestartet? (`docker ps -a`)

**Comment by copystring** [comment]
> Das:
> 
> > Der Container wurde nun sauber erstellt und ist auch, nachdem alles fertig ist noch da.
> 
> und das :
> 
> > Des Weiteren muss der eBesucher Container manuell gestartet werden.
> 
> Schließt sich gegenseitig aus. Denn der Container wird beendet, damit das Firefox Profil gesichert werden kann, und dann per restarter wieder gestartet.

Merkwürdig. Das Verhalten kann ich jedoch wiederholt reproduzieren.

> 
> Also entweder funktioniert der Restarter, bedeutet, nach dem erstellen ist der Container da, oder er funktioniert nicht und dann kann der Container nicht da sein, das müsstest du nochmal austesten (`bash /root/ebesucher/restarter.sh`). Wenn das funktioniert, was genau muss dann mauell gestartet werden?

Du meinst bestimmt `bash /root/ebesucher/restart.sh` das habe ich ausgeführt. `/root/ebesucher/restarter.sh` gab es nicht. 
Sollte dabei irgendwas im Terminal stehen? Es fühlt sich an, als ob da einfach nichts passiert. Es ist einfach direkt fertig.
Wie auch immer, wenn ich das ausführe, wird der eBesucher Container nicht gestartet und auch kein watchtower Container erstellt.
> 
> Das Skript checkt eigentlich, ob einer der Services läuft und falls ja, wird Watchtowerr ebenfalls erstellt. Da ich das ebenfalls überprüft hatte (War ja ebenfalls in der 1. Meldung) bräuchte ich auch hier mehr Infos. Wurde es einfach übersprungen, gabs eine Fehlermeldung, oder wurde der Container eventuell erstellt aber nicht gestartet? (`docker ps -a`)

Ich habe keine Fehlermeldung gesehen. Wird kein Protokoll irgendwo erstellt? Die Dialoge überdecken ja sämtliche Befehle bzw. diese sind nur sehr kurz sichtbar, wenn zum nächsten Dialog gewechselt wird. Vielleicht wird watchtower nicht erstellen, da eBesucher nicht läuft?

```
docker ps -a
CONTAINER ID   IMAGE                           COMMAND        CREATED        STATUS         PORTS                                                                                            NAMES
c40a9e737ce8   jlesage/firefox                 "/init"        2 hours ago    Up 2 minutes   5900/tcp, 0.0.0.0:3000->5800/tcp, :::3000->5800/tcp                                              ebesucher
6269489f93ee   portainer/portainer-ce:latest   "/portainer"   20 hours ago   Up 20 hours    0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp, 9000/tcp   portainer
```
Portainer hatte ich mir nur der Einfachheit halber installiert.

**Comment by Pakobbix** [comment]
hmm komisch, das restarter skript sollte definitiv nicht einfach beendet werden. Selbst wenn der Docker Befehl (docker stop und docker rm) nicht ausgeführt werden, sollte spätestens beim sleep eine Minute vergehen, bevor du das Terminal wieder aktiv nutzen kannst.

Ein log für den Watchtowerr gibts nicht wirklich, wenn du keine Ausgabe hattest, dann wurde schlicht watchtowerr nicht ausgeführt, da kein container gefunden wurde, der ebesucher traffmonetizer peer2profit IPRoyal packetstream oder honeygain heißt.

Die "GUI" überdeckt zwar die ausgabe, aber sie ist dennoch spätestens nach dem letzten Dialog sichtbar. 

Hattest du vor dem `docker ps -a` ebesucher manuell neugestartet? Denn es sieht so aus, als ob der restart funktioniert hätte "Up 2 minutes".

Falls du es manuell neugestartet hattest, könnte ich mir vorstellen, dass bei der restart.sh der eintrag für die CPU Cores fehlt. Ich habe zwar ein failsafe eingebaut bei der Erstellung aber noch nicht im restart skript. Eventuell wurde das bei dir nicht aktualisiert/übernommen.

Das restart.sh skript ist ausschließlich dafür da, zu jeder vollen Stunde ebesucher zu schließen und zu löschen, das aktuelle Firefox Profil zu löschen, aus der Sicherung wiederherzustellen und dann ebesucher erneut zu starten/erstellen. 

Watchtowerr wird nur bei der Ersteinrichtung erstellt (sofern es nicht vorher schon ein Watchtowerr gibt und auch nur, falls ein Service überhaupt exestiert).

Ich kann auch leider dein Problem nicht mehr nachvollziehen. Daher kann ich dir auch leider gerade nicht mehr weiterhelfen.

https://user-images.githubusercontent.com/6762686/224571982-b2aa4b24-72d6-43de-a8b9-c2419a6522ad.mp4

**Comment by copystring** [comment]
OK. Ich habe den lxc gelöscht und neu erstellen. Dann dein Script erneut durchgeführt. In dem frischen System lief dann alles durch. War wohl ein merkwürdiger Zustand, da das Script ja erst einen Fehler hatte. Nun wird alles sauber erstellt. Danke!
