### ISSUE TITLE
Funktioniert es auch im LXC Container?

### ISSUE THREAD

**Issue by tigerthrasher1** [Pakobbix/passive-income#4]
Hi,

sorry, wenn die Frage etwas blöd erscheint, aber funktioniert dein Skript auch mit Proxmox und LXC Containern mit x86 Architektur, da das bereits mit Docker läuft?

LG

**Comment by Pakobbix** [comment]
Genau so läuft es auch bei mir. Proxmox 7.4 mit einem Ubuntu 22.04 LXC und der test LXC ist ein Debian 11.

Falls du es verwenden möchtest, sollte ich dich aber darauf hinweisen, dass es wichtig ist, die Startseite auf die surfbar umzustellen für ebesucher, da es probleme gibt, wenn man dies als env eingibt (so wie es meine skript bisher getan hat)

**Comment by tigerthrasher1** [comment]
Cool, funktioniert jetzt bei mir auch so, Danke!
