### ISSUE TITLE
Traffmonetizer Einrichtung schlägt fehl

### ISSUE THREAD

**Issue by DynamoRonny** [Pakobbix/passive-income#5]
Direkt bei der Eingabe des Tokens für Treaffmonetizer schlägt die Einrichtung leider fehl:

![image](https://github.com/Pakobbix/passive-income/assets/55409571/6939a9a1-0050-4c6f-979a-7e24d5fcb562)

Den entsprechenden Token traue ich mir zu, richtig von der webpage kopiert zu haben. Habe es nun auch schon 4 mal versucht und immer den Fehler erhalten.

**Comment by Pakobbix** [comment]
Hi, sry für die späte Rückmeldung. Github schickt mir irgendwie keine Benachrichtigungen/Alarme mehr.

Dachte eigentlich hätte das schon behoben, habe das jetzt nachgeholt. 

Statt einfach den Docker container upzudaten, hatte Traffmonetizer einen neuen erstellt und den alten gelöscht, daher ging die Installation nicht mehr.

**Comment by DynamoRonny** [comment]
Super Sache, danke dir für den Fix.
